#Filebeat for Kubernetes
filebeat.prospectors:
-
  paths: /containerlogs/*/*.log
  # Exclude Google Ingress healthchecks
  exclude_lines: [ "GET / " , '"hostname":"{{HOSTNAME}}"' ]
  document_type: filebeat-docker-logs
name: {{SHIPPER_NAME}}
logging.files:
  rotateeverybytes: 10485760
output.logstash:
  hosts: [ "{{LOGSTASH_HOST}}:{{LOGSTASH_PORT}}" ]
  # don't worry about TLS within k8 cluster
  # For debugging.
output.file:
  path: "/tmp/filebeat"
