#Filebeat for Kubernetes
filebeat.prospectors:
-
  paths:
  - /containerlogs/*/*.log
  # Exclude Google Ingress and kube-system healthchecks
  exclude_lines: [ "GET / " , "nanny_lib.go" ]
  document_type: filebeat-docker-logs
  json.add_error_key: true
  json.message_key: log
name: {{SHIPPER_NAME}}
logging.files:
  rotateeverybytes: 10485760
output.logstash:
  hosts: [ "{{LOGSTASH_HOST}}:{{LOGSTASH_PORT}}" ]
  ssl.enabled: true
  ssl.certificate: "/tls/beats.crt"
  ssl.key: "/tls/beats.key"
  ssl.certificate_authorities: [ "/tls/ca.crt" ]
  ssl.verification_mode: none
